import SessionProvider from '@/components/session provider/SessionProvider';
import './globals.css'
import { Inter, Nunito_Sans,Poppins } from 'next/font/google'
import { getServerSession } from 'next-auth';

import TopNavbar from '@/components/navbar/TopNavbar';
import Footer from '@/components/footer/Footer';
import "bootstrap/dist/css/bootstrap.css";
import { authOptions } from "@/services/authOptions";
import Navbar from '@/components/navbar/Nav';


const inter = Inter({ subsets: ['latin'] })
const nunitoSans = Nunito_Sans({subsets:['latin']});


export const metadata = {
  title: 'Car Rental',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <SessionProvider session={session}>
          <TopNavbar/>
          <main>{children}</main>
          <Footer/>
        </SessionProvider>
      </body>
    </html>
  );
}
